### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by katesteinmeyer** [katesteinmeyer/Weather-Mobile-Web-App#1]
@DiyahM 
@Keenahn
@LijieZhou

Attached wireframes for the weather web mobile app.
<img width="850" alt="weather_app_wireframes" src="https://cloud.githubusercontent.com/assets/3793880/9648506/4e27455a-519e-11e5-9c9b-4fddae947f3d.png">

**Comment by DiyahM** [comment]
Hi @katesteinmeyer -- Got it! Thanks for submitting this. Sorry for the delay in response, I wanted to checkin with the other instructors before commenting. Just clarifying -- This is a responsive web app? For example: the intent is not to submit to an app store. But the user can access from a mobile browser?

Other than that, looks good to me. Here's one of the weather apis that you can use http://openweathermap.org/api. But there are plenty of others as well.

Let me know if you have any additional questions.
-Diyah

**Comment by ellatronic** [comment]
Hey @katesteinmeyer ,

I'm one of your classmates at Hackbright. Do you mind if I join you on your weather app project?

-Ella

**Comment by katesteinmeyer** [comment]
@DiyahM Yes, it will be mobile responsive.
@ellatronic Sure! I'll add you to the project.
